import {NextResponse} from "next/server";
import {prisma} from "../../../../../prisma/db";
import {helper} from "../../../../../utils/Helper";
import {GET as userRoute} from "../../../users/route";

export async function GET(request,{params}) {
    try{
        const response = await userRoute(request);
        const {id} = await params;


        if(response.status !== 200){
            return response;
        }
        const responseData = await response.json();
        if(responseData.user.role !== "ORGANIZER"){
            return NextResponse.json({error:"Not authorized!"}, {status:403});
        }

        const eventId =   parseInt(id);

        if(isNaN(eventId)){
            return NextResponse.json({error: "Invalid event"}, {status: 400});
        }


        const event = await prisma.event.findUnique({
            where: { id: eventId },
            include: {
                bookings: {
                    include: {
                        user: {
                            select: {
                                id: true,
                                name: true,
                                email: true
                            }
                        }
                    }
                }
            }
        }); //This func generated by ChatGPT

        if(!event){
            return NextResponse.json({error: "Event not found"}, {status: 404});
        }

        if(parseInt(responseData.user.userId) !== event.organizerId){
            return NextResponse.json({error: "Forbidden event"}, {status: 403});
        }

        const soldTicketCount = event.bookings.length

        return NextResponse.json({event, number_of_sold_tickets: soldTicketCount, attendeeList:event.bookings}, {status:200});
    }catch(error){return helper.errors.INTERNAL_SERVER_ERROR();}
}