import {GET as userRoute} from "../../../users/route";
import {NextResponse} from "next/server";
import {prisma} from "../../../../../prisma/db";
import {helper} from "../../../../../utils/Helper";

export async function POST(request,{params}) {
    try{
        const response = await userRoute(request);
        const {id} = await params;

        if(response.status !== 200){
            return response;
        }

        const responseData = await response.json();

        const eventId =   parseInt(id);

        if(isNaN(eventId)){
            return NextResponse.json({error: "Invalid event"}, {status: 400});
        }
        const event = await prisma.event.findUnique({where:{id:eventId}});

        if(!event){
            return NextResponse.json({error: "Event not found"}, {status: 404});
        }


        //Generated by ChatGPT
        // ❗ Count current bookings
        const bookingCount = await prisma.booking.count({
            where: { eventId }
        });

        if (bookingCount >= event.capacity) {
            return NextResponse.json({ error: "Event is full" }, { status: 400 });
        }

        // ❗ Prevent duplicate booking
        const existingBooking = await prisma.booking.findFirst({
            where: {
                userId: responseData.user.userId,
                eventId
            }
        });

        if (existingBooking) {
            return NextResponse.json({ error: "Already booked" }, { status: 400 });
        }

       const booking = await prisma.booking.create({
            data: {
                userId: responseData.user.userId,
                eventId
            }
        });

        return NextResponse.json(booking, { status: 201 });

    }catch(error){return helper.errors.INTERNAL_SERVER_ERROR();}
}